# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab6p1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='image_label',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
